---
title: Inanc.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: İnanç Çakıl
email: inanc.cakil@gmail.com
keywords: Software Engineer
skills: Hi. I’m inanç, a software developer from Ankara, Turkey
baseurl: 
social:
- title: linkedin
  url: https://www.linkedin.com/in/inanccakil/
- title: github
  url: https://github.com/inanc
- title: twitter
  url: https://twitter.com/inanccakil
google_verify: 
bing_verify: 
color:
  primary: 74aab9
  primary-rgb: 33, 150, 243
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1
markdown: kramdown
permalink: pretty
theme: jekyll-theme-cayman
